### ISSUE TITLE
Cannot use module with `enabled` set to false

### ISSUE THREAD

**Issue by ByJacob** [cloudposse/terraform-aws-backup#56]
### Describe the Bug

Module cannot be used when enabled switch is set to false

### Expected Behavior

Module don;'t return error

### Steps to Reproduce

1. Get example
2. Set `enabled` to false

### Screenshots

- OS Linux
- Version: Manjaro
- Module: 0.14.1
- Terraform: 1.3.6

### Additional Context

```
│ Error: Error in function call
│ 
│   on ../../modules/backup/main.tf line 8, in locals:
│    8:   vault_name       = coalesce(var.vault_name, module.this.id)
│     ├────────────────
│     │ while calling coalesce(vals...)
│     │ module.this.id is ""
│     │ var.vault_name is null
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments.
```

### Current workaround

```tf
module "backup" {

  count = var.backup_enable ? 1 : 0

  source         = "cloudposse/backup/aws"
  namespace = var.namespace
  stage          = var.stage
  name          = var.name
  enabled      = var.backup_enable
  ...
}
```

**Comment by sebastienrospars** [comment]
We have the same issue when we want to disable this module. Thanks for the pull request, and I hope it will be merged soon !

**Comment by ByJacob** [comment]
> We have the same issue when we want to disable this module. Thanks for the pull request, and I hope it will be merged soon !

I added how to get workaround this problem in the description. I hope this will help.

**Comment by sebastienrospars** [comment]
Thanks for the workaround ! I will use it as long as this issue is not resolve.
